---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-buildpack-memory-calculator
    tag: latest

inputs:
- name: java-buildpack-memory-calculator
  path: gopath/src/github.com/cloudfoundry/java-buildpack-memory-calculator

run:
  path: gopath/src/github.com/cloudfoundry/java-buildpack-memory-calculator/ci/build.sh

params:
  ARTIFACTORY_REPOSITORY: libs-release-local
  VERSION:                3.11.0.RELEASE

  ARTIFACTORY_USERNAME:
  ARTIFACTORY_PASSWORD:
